In [27]:
import ray
import os
from pyhdfs import HdfsClient
import pandas as pd

In [29]:
nodes = ["127.0.0.1"]
client = HdfsClient(hosts=nodes, user_name="bigdata2022-VirtualBox")
df=pd.read_csv(client.open("hdfs://localhost:9870/user/bigdata2022/datasets/big_data_project/taxi_dataset_EDA.csv"))

In [30]:
df.head()

,Unnamed: 0,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_month,dropoff_month,...,dropoff_day_Monday,dropoff_day_Saturday,dropoff_day_Sunday,dropoff_day_Thursday,dropoff_day_Tuesday,dropoff_day_Wednesday,store_and_fwd_flag_Y,pickup_timezone,dropoff_timezone,distance
0,0,2,1,-73.982155,40.767937,-73.964630,40.765602,455,3,3,...,1,0,0,0,0,0,0,3,3,0.931401
1,1,1,1,-73.980415,40.738564,-73.999481,40.731152,663,6,6,...,0,0,1,0,0,0,0,4,4,1.122207
2,2,2,1,-73.979027,40.763939,-74.005333,40.710087,2124,1,1,...,0,0,0,0,1,0,0,2,2,3.968637
3,3,2,1,-74.010040,40.719971,-74.012268,40.706718,429,4,4,...,0,0,0,0,0,1,0,3,3,0.923307
4,4,2,1,-73.973053,40.793209,-73.972923,40.782520,435,3,3,...,0,1,0,0,0,0,0,2,2,0.738763